service: echoMessageService
frameworkVersion: '2'

package:
  artifact: 'build/libs/message-handler-0.0.1-SNAPSHOT-aws.jar'

provider:
  name: aws
  runtime: java11
  region: eu-central-1
  memorySize: 1024
  timeout: 20
  endpointType: REGIONAL
  environment:
    botToken: ${env:CONFERENCE_TELEGRAM_BOT_TOKEN}

functions:
  echoMessage:
    handler: co.laptev.messagehandler.MessageHandler
    events:
      - http:
          path: /
          method: post
          async: true